version: '3.1'

services:
  lavalink:
    image: fredboat/lavalink:master
    restart: always
    logging:
      driver: awslogs
      options:
         awslogs-group: pixiebot
         awslogs-region: us-east-2
         awslogs-stream-prefix: lavalink
    volumes:
      - ./lava_application.yml:/opt/Lavalink/application.yml

  pixiebot:
    build: $ECR_REPOSITORY:$IMAGE_TAG
    image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    restart: always
    logging:
      driver: awslogs
      options:
         awslogs-group: pixiebot
         awslogs-region: us-east-2
         awslogs-stream-prefix: discordbot
    depends_on:
        - lavalink